// <auto-generated />
using System;
using ElektriKalkulaator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElektriKalkulaator.Data.Migrations
{
    [DbContext(typeof(ElektriKalkulaatorContext))]
    [Migration("20260429200202_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElektriKalkulaator.Core.Domain.CalculationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BreakerAmperes")
                        .HasColumnType("int");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CircuitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomsFrom")
                        .HasColumnType("int");

                    b.Property<int>("RoomsTo")
                        .HasColumnType("int");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WireCrossSectionMm2")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("CalculationRules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            BreakerAmperes = 10,
                            BuildingType = "korterelamu",
                            CircuitType = "lighting",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomsFrom = 1,
                            RoomsTo = 999,
                            RuleName = "Korterelamu valgustus",
                            WireCrossSectionMm2 = 1.5m
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            BreakerAmperes = 16,
                            BuildingType = "korterelamu",
                            CircuitType = "socket",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomsFrom = 1,
                            RoomsTo = 999,
                            RuleName = "Korterelamu pistikud",
                            WireCrossSectionMm2 = 2.5m
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            BreakerAmperes = 32,
                            BuildingType = "korterelamu",
                            CircuitType = "stove",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomsFrom = 1,
                            RoomsTo = 999,
                            RuleName = "Korterelamu pliit",
                            WireCrossSectionMm2 = 6.0m
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000004"),
                            BreakerAmperes = 10,
                            BuildingType = "eramu",
                            CircuitType = "lighting",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomsFrom = 1,
                            RoomsTo = 999,
                            RuleName = "Eramu valgustus",
                            WireCrossSectionMm2 = 1.5m
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000005"),
                            BreakerAmperes = 16,
                            BuildingType = "eramu",
                            CircuitType = "socket",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomsFrom = 1,
                            RoomsTo = 999,
                            RuleName = "Eramu pistikud",
                            WireCrossSectionMm2 = 2.5m
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000006"),
                            BreakerAmperes = 32,
                            BuildingType = "eramu",
                            CircuitType = "stove",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomsFrom = 1,
                            RoomsTo = 999,
                            RuleName = "Eramu pliit",
                            WireCrossSectionMm2 = 6.0m
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000007"),
                            BreakerAmperes = 10,
                            BuildingType = "ärihoone",
                            CircuitType = "lighting",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomsFrom = 1,
                            RoomsTo = 999,
                            RuleName = "Ärihoone valgustus",
                            WireCrossSectionMm2 = 1.5m
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000008"),
                            BreakerAmperes = 16,
                            BuildingType = "ärihoone",
                            CircuitType = "socket",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomsFrom = 1,
                            RoomsTo = 999,
                            RuleName = "Ärihoone pistikud",
                            WireCrossSectionMm2 = 2.5m
                        });
                });

            modelBuilder.Entity("ElektriKalkulaator.Core.Domain.PowerboxCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RulesApplied")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PowerboxCalculations");
                });

            modelBuilder.Entity("ElektriKalkulaator.Core.Domain.PowerboxComponents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalculationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CircuitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("WireCrossSectionMm2")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId");

                    b.HasIndex("ProductId");

                    b.ToTable("PowerboxComponents");
                });

            modelBuilder.Entity("ElektriKalkulaator.Core.Domain.PowerboxRequirements", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CalculationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FloorCount")
                        .HasColumnType("int");

                    b.Property<bool>("HasElectricStove")
                        .HasColumnType("bit");

                    b.Property<int>("LightCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int");

                    b.Property<int>("SocketCount")
                        .HasColumnType("int");

                    b.Property<int>("SwitchCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAreaM2")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId")
                        .IsUnique();

                    b.ToTable("PowerboxRequirements");
                });

            modelBuilder.Entity("ElektriKalkulaator.Core.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("RatedCurrent")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WireCrossSectionMm2")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            Brand = "ABB",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1-pooluseline kaitselüliti B10A, 6kA",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ABB S201-B10 Kaitselüliti 10A",
                            Price = 8.50m,
                            RatedCurrent = 10m,
                            StockQuantity = 150,
                            Voltage = 230m,
                            WireCrossSectionMm2 = 1.5m
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            Brand = "ABB",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1-pooluseline kaitselüliti B16A, 6kA",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ABB S201-B16 Kaitselüliti 16A",
                            Price = 9.20m,
                            RatedCurrent = 16m,
                            StockQuantity = 200,
                            Voltage = 230m,
                            WireCrossSectionMm2 = 2.5m
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            Brand = "ABB",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1-pooluseline kaitselüliti B32A, 6kA",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ABB S201-B32 Kaitselüliti 32A",
                            Price = 12.80m,
                            RatedCurrent = 32m,
                            StockQuantity = 80,
                            Voltage = 230m,
                            WireCrossSectionMm2 = 6.0m
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            Brand = "Schneider",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1-pooluseline kaitselüliti B10A",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Schneider Easy9 B10A",
                            Price = 7.90m,
                            RatedCurrent = 10m,
                            StockQuantity = 120,
                            Voltage = 230m,
                            WireCrossSectionMm2 = 1.5m
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            Brand = "Schneider",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1-pooluseline kaitselüliti B16A",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Schneider Easy9 B16A",
                            Price = 8.50m,
                            RatedCurrent = 16m,
                            StockQuantity = 180,
                            Voltage = 230m,
                            WireCrossSectionMm2 = 2.5m
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000006"),
                            Brand = "Draka",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Valgustuse juhe, müüakse meetrites",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NYM-J 3x1.5mm² kaabel (1m)",
                            Price = 1.20m,
                            RatedCurrent = 10m,
                            StockQuantity = 5000,
                            Voltage = 230m,
                            WireCrossSectionMm2 = 1.5m
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000007"),
                            Brand = "Draka",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pistikute juhe, müüakse meetrites",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NYM-J 3x2.5mm² kaabel (1m)",
                            Price = 1.85m,
                            RatedCurrent = 16m,
                            StockQuantity = 5000,
                            Voltage = 230m,
                            WireCrossSectionMm2 = 2.5m
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000008"),
                            Brand = "Draka",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pliidi juhe, müüakse meetrites",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NYM-J 3x6mm² kaabel (1m)",
                            Price = 3.60m,
                            RatedCurrent = 32m,
                            StockQuantity = 2000,
                            Voltage = 230m,
                            WireCrossSectionMm2 = 6.0m
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000009"),
                            Brand = "ABB",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "2-pooluseline rikkevoolukaitsme 40A 30mA",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ABB F202 AC-40/0.03 RCD 40A",
                            Price = 42.00m,
                            RatedCurrent = 40m,
                            StockQuantity = 50,
                            Voltage = 230m
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000010"),
                            Brand = "ABB",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pinna-paigaldusega kilbi korpus 12 moodulile",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ABB Mistral41F 12 mooduli kilp",
                            Price = 28.50m,
                            RatedCurrent = 0m,
                            StockQuantity = 30,
                            Voltage = 230m
                        });
                });

            modelBuilder.Entity("ElektriKalkulaator.Core.Domain.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automaatkaitselülitid (MCB) ABB, Schneider, Hager",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kaitselülitid"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "NYM-J ja NYY kaablid 1.5mm², 2.5mm², 6mm²",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Juhtmed"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rikkevoolukaitsmed (RCD/RCCB) 25A, 40A, 63A",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RCD / Rikkevoolukaitsmeid"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ühenduskarbid ja klemmiribad",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Klemmid"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Plastik ja metallist kilbi korpused 4-24 mooduli jaoks",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kilbi korpused"
                        });
                });

            modelBuilder.Entity("ElektriKalkulaator.Core.Domain.PowerboxComponents", b =>
                {
                    b.HasOne("ElektriKalkulaator.Core.Domain.PowerboxCalculation", "Calculation")
                        .WithMany("Components")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElektriKalkulaator.Core.Domain.Product", "Product")
                        .WithMany("PowerboxComponents")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calculation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ElektriKalkulaator.Core.Domain.PowerboxRequirements", b =>
                {
                    b.HasOne("ElektriKalkulaator.Core.Domain.PowerboxCalculation", "Calculation")
                        .WithOne("Requirements")
                        .HasForeignKey("ElektriKalkulaator.Core.Domain.PowerboxRequirements", "CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("ElektriKalkulaator.Core.Domain.Product", b =>
                {
                    b.HasOne("ElektriKalkulaator.Core.Domain.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ElektriKalkulaator.Core.Domain.PowerboxCalculation", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("ElektriKalkulaator.Core.Domain.Product", b =>
                {
                    b.Navigation("PowerboxComponents");
                });

            modelBuilder.Entity("ElektriKalkulaator.Core.Domain.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
